### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by jugglingcats** [jxyden14/nedyaj#1]
Hi @jxyden14, just want to make sure you get an email when I mention you in an issue. Hope you are having a nice half term.

Please be aware that this repository and all issues are public so don't add any personal info!

Let me know if you have done any coding, and what you plan look at before we meet next.

**Comment by jugglingcats** [comment]
@jxyden14 are you getting notifications?

**Comment by jugglingcats** [comment]
@jxyden14, please add a comment to this issue so I know you are receiving the github emails, tx

**Comment by jxyden14** [comment]
Sir I honestly got no clue how you send messages on GitHub

**Comment by jugglingcats** [comment]
Hi @jxyden14, you replied by email and that works...! Or you can click on the link ("view it on GitHub") at the bottom of the emails and go to github and enter your reply there.

You were going to share your personal statement for college application. You could create another issue for that (click New Issue top right), or provide link to google drive doc like we discussed.

**Comment by jxyden14** [comment]
oh so this is where- yeah Sir I finally got it:)
