### ISSUE TITLE
Coding help!

### ISSUE THREAD

**Issue by jxyden14** [jxyden14/nedyaj#11]
Hello Sir, Hope you are doing well. I've finally managed to create my first "issue" onto GitHub, was always wondering how this was done. I have a question for you, I was working on some programming last night and came across this problem, could you please check and let me know if it's correct / there is a better solution :)

### The following program will calculate a car’s speed around a racing track. When the code is run it will result in syntax errors due to the wrong data types being used.

time = input(“Enter your time in seconds - e.g 73.4 ”)
distance = input(“Enter your distance in miles - e.g. 5.7 ”)
timeHours = time / 60^2
speed = distance / time
print(“Your speed = ” + speed)

### Rewrite the program using casting so that data types will be correct.

MY RESPONSE:
_time = float(input(“Enter your time in seconds - e.g 73.4 ”))
distance = float(input(“Enter your distance in miles - e.g. 5.7 ”))
timeHours = time / 60^2
speed = distance / time
Print(“Your speed = ” + speed)_

**Comment by jugglingcats** [comment]
Hi Jayden!

That looks like it should work. I am curious what will happen if you enter an input that is not a number. It would be nice if your program could detect this and display an error message.

Also, even if there is no syntax error I don't think the output will be correct - can you spot any other issue with the code as it is?

**Comment by jugglingcats** [comment]
Hi @jxyden14
