### ISSUE TITLE
Meeting discussions (Feb)

### ISSUE THREAD

**Issue by jxyden14** [jxyden14/nedyaj#13]
Hello Sir, Hope you are keeping well. I have set up this issue so that we can arrange for what we want to discuss during our meetings so that if required we can come prepared with some relevant info which perhaps will enhance the understanding of it...

For tomorrow, I prepared this presentation on Stoicism which my class used for their assembly today, can I present it as part of the meeting? 

Kind regards,
Jayden

**Comment by jugglingcats** [comment]
That sounds great @jxyden14, I look forward to it!! I don't have much planned to discuss but would be good to get an update on the other items we have here on Github (coding activity, etc).

**Comment by jugglingcats** [comment]
Hi @jxyden14, I was very impressed and moved by your talk today - thanks for sharing with me. Could I possibly get a copy of it? Have a good weekend

**Comment by jxyden14** [comment]
Sure, here you go!

https://docs.google.com/presentation/d/1vAd921P0NF0UNslbsA5bf5f9VQueDFBRjx4iXPEe778/edit?usp=sharing
