### ISSUE TITLE
Personal statement

### ISSUE THREAD

**Issue by jugglingcats** [jxyden14/nedyaj#2]
Hi @jxyden14 you were going to send me the text for your personal statement for me to comment on.

**Comment by jxyden14** [comment]
Sir is there a way I can link a google doc into this or can I just send it
via email?

**Comment by jugglingcats** [comment]
Just reply to this email with the Google Doc link...

**Comment by jxyden14** [comment]
Here is the google doc link Sir.

Have a good evening :)

https://docs.google.com/document/d/1k3tTu1wZC--nc7Yx0RgSIhzZUXbqMyqQb8I5n0QtpyU/edit

**Comment by jugglingcats** [comment]
Hi Jayden you need to make it viewable/editable by anyone with the link (it
might then be a different link)
 Tx

**Comment by jxyden14** [comment]
Hello Sir, I’ve updated it now, hope it works this time…

Have an awesome day 💯

**Comment by jugglingcats** [comment]
Thanks Jayden it works 🎉

**Comment by jugglingcats** [comment]
Had a quick look and think it's already very good - well done! Will make some small comments later today for us to discuss tomorrow.

**Comment by jugglingcats** [comment]
Hi Jayden I couldn't edit/comment on your doc so created another one here: https://docs.google.com/document/d/1Xpz6z0cloTLOYAScSnnR3c_bk3c1i9nLNpvbIL3yEIM/edit?usp=sharing

We can run through tomorrow...

**Comment by jxyden14** [comment]
Sir thank you so much for this but I cannot fit extra bits into my
application.... (there is a character limit + I've sent it on Monday
because I had to ask the HOY to give me a referral)...

I'll try to edit my application though, hope it works.

Have a good evening, Sir.
