### ISSUE TITLE
Meeting times

### ISSUE THREAD

**Issue by jugglingcats** [jxyden14/nedyaj#4]
Hi @jxyden14, hope you're having a good week.

We said we wouldn't meet this week because you have exams, but I'm happy to meet tomorrow 3 Dec as normal if you'd like to. Let me know if you want me to come in!

**Comment by jxyden14** [comment]
Hello Sir,

hope you are having a great week too.

Unfortunately, school is closed tomorrow, so we cannot meet until the end
of the exams... Hope to make the day productive by revising for my Computer
Science exam next week.

Sorry to let you down, have a great rest of the week Sir.

Kind regards,
Jayden

**Comment by jugglingcats** [comment]
Hi Jayden I hope your exams are going well! Just want to confirm we are not meeting this Friday.

**Comment by jxyden14** [comment]
That's alright Sir, looking forward to meeting next week then.

Have a wonderful rest of the week.

**Comment by jugglingcats** [comment]
@jxyden14 I am currently self-isolating at home because I had a positive lateral flow test on Friday (and several since). I also have two negative PCR tests, but the covid app is telling me to stay at home and isolate. I am going to do another PCR tomorrow and more lateral flows and if all clear I would still like to meet on Friday -- if you still want to on your last day of course. Either way I will think of some coding for you and we can hopefully work on them together over the holidays!

**Comment by jxyden14** [comment]
Hello Sir

I feel so bad to tell you this but our school actually closes tomorrow (for
Y11) so I won’t be in on Friday either….

So sorry once again.

Have a good rest of the week Sir.

**Comment by jxyden14** [comment]
P.S. hope you feel better soon, COVID is really messing things up for us

**Comment by jugglingcats** [comment]
I actually don't have any symptoms so it's just tedious being stuck at home - but am getting lots done! Thanks for letting me know about Friday.

**Comment by jugglingcats** [comment]
Hi @jxyden14 just confirming we are starting our meetings again on Friday 7 Jan. I am away from 9-20 Jan so we won't be able to meet on 14th.

**Comment by jxyden14** [comment]
Good evening Sir, hope you had a lovely festive break 🎉

Happy New Year!! Wishing you and your precious family a happy, prosperous
and grace-filled 2022. May it bring only great news and positive emotions ❤️

As for the mentoring session, it’s fine by me for tomorrow, looking forward
to it! ✅


Hope you have a lovely year ahead, filled with lots of success, prosperity
and good health… 💯

Kind regards,
Jayden

**Comment by jugglingcats** [comment]
Hi Jayden meant to say thank you for your kind message for the year! I hope your 2022 is filled with fun and happiness, and that you are successful with all your many new year resolutions!
