### ISSUE TITLE
GCSE Edexcel grade boundaries

### ISSUE THREAD

**Issue by jugglingcats** [jxyden14/nedyaj#5]
Hi @jxyden14 just looking through my notes and I was going to find you the grade boundaries.

Here is a link to the 2018 grade boundaries: https://qualifications.pearson.com/content/dam/pdf/Support/Grade-boundaries/GCSE/1806-GCSE-9-1-Subject-Grade-Boundaries.pdf

Some highlights:

Maths higher: 84% for level 9; 71% for level 8
Physics: 76.5% for level 9; 67% for level 8
Chemistry: 76.5% for level 9; 66% for level 8
Biology: 72.5% for level 9; 64.5 for level 8
English Language: 83.5% for level 9; 76% for level 8; 69% for level 7
English Literature: 83.5% for level 9; 76% for level 8; 68% for level 7

These change from year to year depending on how well the students do that year, but gives you an idea.

Does this give you encouragement or is more or less what you already thought...?

**Comment by jxyden14** [comment]
Thanks for the information Sir, I expected something similar but now I can
fully say that a 9 isn’t entirely 90%+ 🙏🏼
