### ISSUE TITLE
Holiday coding

### ISSUE THREAD

**Issue by jugglingcats** [jxyden14/nedyaj#7]
Hi @jxyden14, hope you had a great Christmas and you're enjoying some well deserved time off after your exams!

Let me know if you've been doing any coding over the holiday and if you want help with anything. The stock market article I sent you is pretty involved, so if you want something simpler to work on, the Euler problems I mentioned before are a good resource. I particularly like the prime factors one: https://projecteuler.net/problem=3

Always happy to look at code if you're stuck on anything - just shoot me a message on here.

**Comment by jxyden14** [comment]
Hello Sir, hope you are enjoying the holidays as much as I am 😊

I will have a look at the stock market article, was busy helping out in the
church with the festive celebrations over the past few days so will get
that done before our next meeting 👍🏼

Have a nice day Sir,
and a very Happy New Year 2️⃣0️⃣2️⃣2️⃣ 🎉
