### ISSUE TITLE
Coding course

### ISSUE THREAD

**Issue by jugglingcats** [jxyden14/nedyaj#9]
Hi @jxyden14 I had a look at courses but only briefly. Maybe try this one to start as it's not too many hours. If you like the site it has more advanced courses available... If you don't find it helpful just say and I will look for others!

https://www.codecademy.com/learn/connect-four

**Comment by jxyden14** [comment]
Sure Sir, will start from tomorrow onwards. Thank you for taking the time
to find this for me 👍

**Comment by jugglingcats** [comment]
Hi @jxyden14, did you have a chance to start this yet? Is it any good?

**Comment by jxyden14** [comment]
Was going to start on it but a lot of things are going on right now so at
the most I only got the weekends to do so; I will start henceforth ASAP 👍
